[package]
name = "bracket-lib"
version = "0.7.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"
publish = false
description = "Meta-crate holding the entirety of bracket-lib (and exposing it). Use this for the full roguelike toolkit experience."
homepage = "https://github.com/thebracket/rltk_rs"
repository = "https://github.com/thebracket/rltk_rs"
readme = "README.md"
keywords = ["roguelike", "gamedev", "terminal", "console", "ascii", "cp437"]
categories = ["game-engines"]
license = "MIT"

[features]
default = [ "opengl" ]
specs = [ "bracket-geometry/specs" ]
serde = [ "bracket-color/serde", "bracket-geometry/serde", "bracket-random/serde" ]
threaded = [ "bracket-pathfinding/threaded" ]
opengl = [ "bracket-terminal/opengl" ]
curses = [ "bracket-terminal/curses" ]
crossterm = [ "bracket-terminal/crossterm" ]
amethyst_engine_vulkan = [ "bracket-terminal/amethyst_engine_vulkan" ]
amethyst_engine_metal = [ "bracket-terminal/amethyst_engine_metal" ]

[dependencies]
bracket-algorithm-traits = "0.7.0"
bracket-color = { version = "0.7.0", features = [ "rex" ] }
bracket-geometry = "0.7.0"
bracket-noise = "0.7.0"
bracket-pathfinding = "0.7.0"
bracket-random = { version = "0.7.0", features = [ "parsing" ] }
bracket-terminal = { version = "0.7.0", default-features = false }

[workspace]
members = [
    "bracket-algorithm-traits",
    "bracket-color",
    "bracket-geometry",
    "bracket-noise",
    "bracket-pathfinding",
    "bracket-random",
    "bracket-terminal",
    "rltk"
]
