[package]
name = "rltk"
version = "0.1.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
image = "0.19.0"
cgmath = "0.16.1"
glfw = "0.29.0"
glm = "0.2.3"
gl = "0.12.0"
bresenham = "0.1.1"
rayon = "1.1.0"
