[package]
name = "rltk"
version = "0.2.5"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"
publish = false
build = "build.rs"
description = "A CP437/ASCII terminal library and helpers to make creating roguelike games in Rust easy. Similar to libtcod, but aiming to be Rust-native."
homepage = "https://github.com/thebracket/rltk_rs"
repository = "https://github.com/thebracket/rltk_rs"
readme = "README.md"
keywords = ["roguelike", "cp437", "ascii", "virtual terminal", "gamedev"]
categories = ["game-engines", "graphics"]
license = "MIT"
maintenance = { status = "actively-developed" }

[dependencies]
glutin = "0.22.0-alpha1"
winit = "0.20.0-alpha2"
image = "0.22.1"
cgmath = "0.17.0"
bresenham = "0.1.1"
rayon = "1.1.0"
rand = "0.7.0"
rand_xorshift = "0.2.0"
serde= { version = "1.0.98", features = ["derive"], optional = true }
serde_json =  { version = "1.0.40", optional = true }
flate2 = "1.0.9"
byteorder = "1.3.2"

[build-dependencies]
gl_generator = "0.13.0"

[features]
default = []
serialization = [ "serde/derive", "serde_json" ]

