[package]
name = "bracket-color"
version = "0.7.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"
publish = true
description = "RGB and HSV color handling and utilities, including lerp and W3C named colors. Part of the bracket-lib family."
homepage = "https://github.com/thebracket/rltk_rs"
repository = "https://github.com/thebracket/rltk_rs"
readme = "README.md"
keywords = ["roguelike", "gamedev", "RGB", "HSV", "color"]
categories = ["game-engines", "graphics"]
license = "MIT"

[features]
rex = [ "byteorder" ]

[dependencies]
serde = { version = "1.0.104", features = ["derive"], optional = true }
byteorder = { version = "1.3.4", optional = true }
crossterm = { version = "0.16.0", optional = true }

[dev-dependencies]
crossterm = "0.16.0"

[[example]]
name = "colors"
required-features = ["crossterm"]

[[example]]
name = "lerp"
required-features = ["crossterm"]

[[example]]
name = "lerpit"
required-features = ["crossterm"]

[[example]]
name = "lerpit_hsv"
required-features = ["crossterm"]

[[example]]
name = "named_color"
required-features = ["crossterm"]

[[example]]
name = "shades_of_grey"
required-features = ["crossterm"]
