[package]
name = "bracket-color"
version = "0.1.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"
publish = true
description = "RGB and HSV color handling and utilities, including lerp and W3C named colors. Part of the bracket-lib family."
homepage = "https://github.com/thebracket/bracket-color"
repository = "https://github.com/thebracket/bracket-color"
readme = "README.md"
keywords = ["roguelike", "gamedev", "RGB", "HSV", "color"]
categories = ["game-engines", "graphics"]
license = "MIT"

[features]
rex = [ "byteorder" ]

[dependencies]
serde = { version = "1.0.104", features = ["derive"], optional = true }
byteorder = { version = "1.3.4", optional = true }

[dev-dependencies]
crossterm = "0.16.0"
