name: Rust

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check benchmarks
      run: cargo check --benches
    - name: Check examples
      run: |
        cargo check --example ex01-helloworld
        cargo check --example ex02-sparse
        cargo check --example ex03-walking
        cargo check --example ex04-fov
        cargo check --example ex05-dijkstra
        cargo check --example ex06-astar-mouse
        cargo check --example ex07-tiles
        cargo check --example ex08-rex
        cargo check --example ex09-offsets
        cargo check --example ex10-postprocess
        cargo check --example ex11-random
        cargo check --example ex12-simplex
        cargo check --example ex13-textblock
        cargo check --example ex14-dwarfmap
        cargo check --example ex15-specs
        cargo check --example ex16-keyboard
        cargo check --example ex17-wasm-external
        cargo check --example av01-helloworld
        cargo check --example av02-sparse
        cargo check --example av03-walking
        cargo check --example av04-fov
        cargo check --example av05-dijkstra
        cargo check --example av06-astar-mouse
        cargo check --example av07-tiles
        cargo check --example av08-rex
        cargo check --example av09-offsets
        cargo check --example av10-postprocess
        cargo check --example av11-random
        cargo check --example av12-simplex
        cargo check --example av13-textblock
        cargo check --example av14-dwarfmap
        cargo check --example av15-specs
        cargo check --example av16-keyboard
        cargo check --example am01-helloworld
        cargo check --example am02-sparse
        cargo check --example am03-walking
        cargo check --example am04-fov
        cargo check --example am05-dijkstra
        cargo check --example am06-astar-mouse
        cargo check --example am07-tiles
        cargo check --example am08-rex
        cargo check --example am09-offsets
        cargo check --example am10-postprocess
        cargo check --example am11-random
        cargo check --example am12-simplex
        cargo check --example am13-textblock
        cargo check --example am14-dwarfmap
        cargo check --example am15-specs
        cargo check --example am16-keyboard
        cargo check --example curses01-helloworld
        cargo check --example curses02-sparse
        cargo check --example curses03-walking
        cargo check --example curses04-fov
        cargo check --example curses05-dijkstra
        cargo check --example curses06-astar-mouse
        cargo check --example curses07-tiles
        cargo check --example curses08-rex
        cargo check --example curses09-offsets
        cargo check --example curses10-postprocess
        cargo check --example curses11-random
        cargo check --example curses12-simplex
        cargo check --example curses13-textblock
        cargo check --example curses14-dwarfmap
        cargo check --example curses15-specs
        cargo check --example curses16-keyboard
        cargo check --example curses17-wasm-external
