name: Rust

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check benchmarks
      run: cargo check --benches
    - name: Check examples
      run: |
        cargo check ex01-helloworld
        cargo check ex02-sparse
        cargo check ex03-walking
        cargo check ex04-fov
        cargo check ex05-dijkstra
        cargo check ex06-astar-mouse
        cargo check ex07-tiles
        cargo check ex08-rex
        cargo check ex09-offsets
        cargo check ex10-postprocess
        cargo check ex11-random
        cargo check ex12-simplex
        cargo check ex13-textblock
        cargo check ex14-dwarfmap
        cargo check ex15-specs
        cargo check ex16-keyboard
        cargo check ex17-wasm-external
        cargo check av01-helloworld
        cargo check av02-sparse
        cargo check av03-walking
        cargo check av04-fov
        cargo check av05-dijkstra
        cargo check av06-astar-mouse
        cargo check av07-tiles
        cargo check av08-rex
        cargo check av09-offsets
        cargo check av10-postprocess
        cargo check av11-random
        cargo check av12-simplex
        cargo check av13-textblock
        cargo check av14-dwarfmap
        cargo check av15-specs
        cargo check av16-keyboard
        cargo check am01-helloworld
        cargo check am02-sparse
        cargo check am03-walking
        cargo check am04-fov
        cargo check am05-dijkstra
        cargo check am06-astar-mouse
        cargo check am07-tiles
        cargo check am08-rex
        cargo check am09-offsets
        cargo check am10-postprocess
        cargo check am11-random
        cargo check am12-simplex
        cargo check am13-textblock
        cargo check am14-dwarfmap
        cargo check am15-specs
        cargo check am16-keyboard
        cargo check curses01-helloworld
        cargo check curses02-sparse
        cargo check curses03-walking
        cargo check curses04-fov
        cargo check curses05-dijkstra
        cargo check curses06-astar-mouse
        cargo check curses07-tiles
        cargo check curses08-rex
        cargo check curses09-offsets
        cargo check curses10-postprocess
        cargo check curses11-random
        cargo check curses12-simplex
        cargo check curses13-textblock
        cargo check curses14-dwarfmap
        cargo check curses15-specs
        cargo check curses16-keyboard
        cargo check curses17-wasm-external
